/**
 * Regenerates `src/data/catalogue.generated.ts` from the course data files.
 *
 * The catalogue is the light index the home and year pages render from, so
 * those pages never pull the ~70,000 words of lesson prose into the initial
 * chunk. It is derived rather than hand-maintained so lesson counts and course
 * metadata cannot drift from the data they describe.
 *
 *   npm run gen:data      rewrite the catalogue
 *   npm run check:data    fail if the committed catalogue is stale
 *
 * Deliberately imports the year modules rather than `src/data/index.ts`: that
 * module loads years dynamically and pulls in React, neither of which belongs
 * in a build script.
 */
import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import type { Course, CourseSummary, Year } from '../src/types'
import { resources } from '../src/data/resources'
import { year1, year1Courses } from '../src/data/year1'
import { year2, year2Courses } from '../src/data/year2'
import { year3, year3Courses } from '../src/data/year3'
import { year4, year4Courses } from '../src/data/year4'

const OUT = new URL('../src/data/catalogue.generated.ts', import.meta.url)

const years: Year[] = [year1, year2, year3, year4]
const byYear: Course[][] = [year1Courses, year2Courses, year3Courses, year4Courses]
const courses = new Map<string, Course>(byYear.flat().map((c) => [c.id, c]))

const summaries: CourseSummary[] = []
for (const y of years) {
  for (const sem of y.semesters) {
    for (const id of sem.courseIds) {
      const course = courses.get(id)
      if (!course) throw new Error(`${sem.id} lists unknown course "${id}"`)
      summaries.push({
        id: course.id,
        code: course.code,
        title: course.title,
        credits: course.credits,
        stream: course.stream,
        year: y.year,
        lessonCount: course.lessons.length,
        ...(course.prerequisites?.length ? { prerequisites: course.prerequisites } : {}),
      })
    }
  }
}

const listed = new Set(summaries.map((s) => s.id))
const orphans = [...courses.keys()].filter((id) => !listed.has(id))
if (orphans.length) throw new Error(`courses in no semester: ${orphans.join(', ')}`)

const dangling = summaries.flatMap((s) =>
  (s.prerequisites ?? []).filter((p) => !courses.has(p)).map((p) => `${s.id} -> ${p}`),
)
// A warning while generating (so the catalogue can still be rebuilt mid-edit)
// but fatal in --check, which is what gates a commit.
if (dangling.length) {
  const detail = `prerequisites pointing at courses that do not exist: ${dangling.join(', ')}`
  if (process.argv.includes('--check')) throw new Error(detail)
  console.warn(`warning: ${detail}`)
}

// resolveResources() drops ids it cannot find, so a typo in a citation would
// otherwise vanish silently instead of failing.
const badResources: string[] = []
for (const course of courses.values()) {
  for (const id of course.resources ?? []) {
    if (!resources[id]) badResources.push(`${course.id}: ${id}`)
  }
  for (const lesson of course.lessons) {
    for (const id of lesson.resources ?? []) {
      if (!resources[id]) badResources.push(`${course.id}/${lesson.id}: ${id}`)
    }
  }
}
if (badResources.length) {
  throw new Error(`citations of unknown resources: ${badResources.join(', ')}`)
}

const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

const body = `// GENERATED by scripts/gen-catalogue.ts — do not edit by hand.
// Run \`npm run gen:data\` after changing any course data.
import type { CourseSummary } from '../types'

export interface SemesterSummary {
  id: string
  label: string
  courseIds: string[]
}

export interface YearSummary {
  year: 1 | 2 | 3 | 4
  title: string
  theme: string
  semesters: SemesterSummary[]
}

export const years: YearSummary[] = [
${years
  .map(
    (y) => `  {
    year: ${y.year},
    title: ${q(y.title)},
    theme:
      ${q(y.theme)},
    semesters: [
${y.semesters
  .map(
    (s) => `      {
        id: ${q(s.id)},
        label: ${q(s.label)},
        courseIds: [${s.courseIds.map(q).join(', ')}],
      },`,
  )
  .join('\n')}
    ],
  },`,
  )
  .join('\n')}
]

export const courseSummaries: Record<string, CourseSummary> = {
${summaries
  .map(
    (s) => `  ${s.id}: {
    id: ${q(s.id)},
    code: ${q(s.code)},
    title: ${q(s.title)},
    credits: ${s.credits},
    stream: ${q(s.stream)},
    year: ${s.year},
    lessonCount: ${s.lessonCount},${
      s.prerequisites ? `\n    prerequisites: [${s.prerequisites.map(q).join(', ')}],` : ''
    }
  },`,
  )
  .join('\n')}
}

/** Total lessons per year, so the home page can show progress without the prose. */
export const lessonCountByYear: Record<number, number> = {
${years
  .map(
    (y) =>
      `  ${y.year}: ${y.semesters
        .flatMap((s) => s.courseIds)
        .reduce((n, id) => n + courses.get(id)!.lessons.length, 0)},`,
  )
  .join('\n')}
}
`

if (process.argv.includes('--check')) {
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== body) {
    console.error(
      'src/data/catalogue.generated.ts is out of date with the course data.\n' +
        'Run `npm run gen:data` and commit the result.',
    )
    process.exit(1)
  }
  console.log(`catalogue up to date — ${summaries.length} courses`)
} else {
  writeFileSync(OUT, body)
  console.log(`wrote catalogue — ${summaries.length} courses, ${listed.size} listed`)
}
